CHROMA_COLLECTION_NAME = "infobee_rag"

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

CHUNK_SIZE = 700
CHUNK_OVERLAP = 200

GROQ_PRIMARY_MODEL_NAME = "openai/gpt-oss-20b"
GROQ_FALLBACK_MODEL1 = "qwen/qwen3.6-27b"
GROQ_FALLBACK_MODEL2 = "openai/gpt-oss-120b" #Large context and reasoning

GENERATION_TOP_K = 10

MAX_CONTEXT_CHARS_PER_CHUNK = 800

TABLE_DEDUP_OVERLAP_THRESHOLD = 0.7
BOILERPLATE_MIN_REPEAT_FRACTION = 0.5